### SERVER

GET http://localhost:5001/

### Winerys - find alle

GET http://localhost:5001/winery

### Winerys - find ud fra _id

GET http://localhost:5001/winery/60a769c555a0b748f0658a0a

### Winerys POST ny

POST http://localhost:5001/winery
Content-Type: application/json

{
    "country": "Holland",
    "name": "Her er et winery",
    "location": "123456778",
    "description": "Dette her er et rigtig godt sted",
    "mapcoords": "123123",
    "price": "215",
    "adress": "Italy highway",
    "phone": "87642342",
    "mail": "winery@sdfsdf",
    "nearby": "asdasd",
    "openinghrs": "08-17",
    "website": "www.winenowyay.com"
    
      
}

### Winerys - DELETE

DELETE http://localhost:5001/winery/60bf57644a0700310855365b

### Winerys - PUT (ret)

PUT http://localhost:5001/winery/60bf577c4a0700310855365c
Content-Type: application/json

{
    "country": "Germany",
    "name": "Her er et winery",
    "location": "123456778",
    "description": "Dette her er et rigtig godt sted",
    "mapcoords": "123123",
    "price": "215",
    "adress": "Italy highway",
    "phone": "87642342",
    "mail": "winery@sdfsdf",
    "nearby": "asdasd",
    "openinghrs": "08-17",
    "website": "www.winenowyay.com"
    
      
}

