### SERVER

GET http://localhost:5001/

### Winerys - find alle

GET http://localhost:5001/winery

### Winerys - find ud fra _id

GET http://localhost:5001/winery/60a769c555a0b748f0658a0a

### Winerys POST ny

POST http://localhost:5001/winery
Content-Type: application/json

{
    "country": "Italy",
    "name": "Marco Reggio",
    "location": "Castelnuovo Calcea (AT)",
    "description": "Our cellar has been producing wine since 1800, we are in Castelnuovo Calcea, a small village in the heart of Monferrato.",
    "price": "15",
    "adress": "Via Momparone 2/B, 14040",
    "phone": "+390456261292 / +393201133324",
    "mail": "marcoreg@liberoit",
    "openinghrs": "8.30 am - 7 pm",
    "website": "http://www.marcoreg.libero.it",
    "pictures": ""
    
      
}

### Winerys - DELETE

DELETE http://localhost:5001/winery/60bf57644a0700310855365b

### Winerys - PUT (ret)

PUT http://localhost:5001/winery/60bf577c4a0700310855365c
Content-Type: application/json

{
    "country": "Germany",
    "name": "Her er et winery",
    "location": "123456778",
    "description": "Dette her er et rigtig godt sted",
    "price": "215",
    "adress": "Italy highway",
    "phone": "87642342",
    "mail": "winery@sdfsdf",
    "openinghrs": "08-17",
    "website": "www.winenowyay.com",
    "pictures": ""
    
      
}

